name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ruff-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install ruff
        run: pip install ruff

      - name: Run ruff check (fail on issues)
        run: ruff check . --output-format=github